name: tinto-project
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41750356717966497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4375
  lightness: 0.0690567153505981
  saturation: 0.0872347264084965
  rhythmicContrast: 1
purpose: []
